### ISSUE TITLE
If the KMS selector misses, records go silently unencrypted.

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#968] opened 2024-02-08 08:23 UTC
https://github.com/kroxylicious/kroxylicious/issues/967

              I still think this represents a bug. As it allows silent failure of the selector policy.

_Originally posted by @SamBarker in https://github.com/kroxylicious/kroxylicious/pull/932#discussion_r1482234660_

**Comment by SamBarker** [comment] 2024-02-08 08:28
This is a duplicate of https://github.com/kroxylicious/kroxylicious/issues/811 (though the wording here is more explicit)

**Closed by SamBarker** 2024-02-08 08:28 UTC
