### ISSUE TITLE
RecordEncryption in 0.8.0 closes the client connection with `RequestNotSatisfiable`("failed to reserve an EDEK to encrypt N records...") under load

### ISSUE THREAD

**Issue by ddaviesbrackett-dwp** [kroxylicious/kroxylicious#1526] opened 2024-09-24 10:57 UTC
**Describe the bug**
RecordEncryptionFilter in Kroxylicious 0.8.0 closes the client connection with a `RequestNotSatisfiable` exception with a message that begins "failed to reserve an EDEK to encrypt N records" under load when using AWS KMS

**To Reproduce**
1. Configure kroxylicious to use record encryption with AWS KMS, setting max encryptions per DEK unreasonably low (say, 5000), using a single KEK (i.e. do not use $topicName in the KEK selector alias). 
2. Fire a reasonably large number of messages at the proxy - ~3000/second in our test
3. See [RequestNotSatisfiable exception log messages](https://github.com/kroxylicious/kroxylicious/blob/40c71dab8330d110e1e3e2cce1153c7bc79948e8/kroxylicious-filters/kroxylicious-record-encryption/src/main/java/io/kroxylicious/filter/encryption/encrypt/InBandEncryptionManager.java#L118) in the kroxy logs

NB: setting the max encryptions per dek very low in step 1 is not strictly necessary, but does increase the prevalence of the error message.

**Expected behavior**
Kroxy should block  during record production until a DEK is available that can satisfy the request (at least if acks != none). 

**YAML files and logs**

Attach or copy paste your kroxylicious configuration YAML (with sensitive details
like broker address redacted).
```
adminHttp:
  endpoints:
    prometheus: {}
virtualClusters:
  [redacted]:
    tls:
      key:
        privateKeyFile: [redacted]
        certificateFile: [redacted]
      trust:
        storeFile: [redacted]
        storePassword:
          password: [redacted]
        storeType: PKCS12
    targetCluster:
      bootstrap_servers: [redacted-broker-1]:9094,[redacted-broker-2]:9094,[redacted-broker-3]:9094
      tls:
        key:
          privateKeyFile: [redacted]
          certificateFile: [redacted]
        trust:
          storeFile: [redacted]
          storePassword:
            password: [redacted]
          storeType: PKCS12
    clusterNetworkAddressConfigProvider:
      type: PortPerBrokerClusterNetworkAddressConfigProvider
      config:
        bootstrapAddress: [redacted-proxy]:9192
        brokerStartPort: 9193
        numberOfBrokerPorts: 4
    logNetwork: false
    logFrames: false
filters:
- type: RecordEncryption
  config:
    kms: AwsKmsService
    kmsConfig:
      endpointUrl: https://kms.eu-west-2.amazonaws.com
      tls:
      accessKey:
        passwordFile: [redacted]
      secretKey:
        passwordFile: [redacted]
      region: eu-west-2
    selector: TemplateKekSelector
    selectorConfig:
      template: "some-redacted-value-containing-no-replacement-tokens"
    experimental:
      encryptionDekRefreshAfterWriteSeconds: 3600
      encryptionDekExpireAfterWriteSeconds: 7200
      maxEncryptionsPerDek: 5007
```

Attach or copy and paste relevant logs.
```
2024-09-23 10:17:03 <nioEventLoopGroup-5-2> WARN  io.kroxylicious.filter.encryption.RecordEncryptionFilter:106 - failed to encrypt records, cause message: io.kroxylicious.filter.encryption.encrypt.RequestNotSatisfiable: failed to reserve an EDEK to encrypt 99 records for topic uk.gov.dwp.test.performance.0 partition 0 after 3 attempts
2024-09-23 10:17:03 <nioEventLoopGroup-5-2> WARN  io.kroxylicious.proxy.internal.FilterHandler:289 - [id: 0xe9b77889, L:/XXX.XXX.XXX.XXX:56406 - R:broker_hostname/XXX.XXX.XXX.XXX:9094]: Filterrequest for RecordEncryptionFilter@1224749844 PRODUCE ended exceptionally - closing connection. Cause message io.kroxylicious.filter.encryption.encrypt.RequestNotSatisfiable: failed to reserve an EDEK to encrypt 99 records for topic uk.gov.dwp.test.performance.0 partition 0 after 3 attempts
``` 
**Additional context**
* We've only run this with AWS KMS, not with either of the other two KMS implementations; this bug may not be dependent on the kms impl but also it might be!!
* We have the capacity to execute variations on the tests above if doing so would help either characterise, or prove resolution of, the issue
* We believe this issue to be something to do with a cross-thread race condition in the Caffeine cache that actually caches the EDEKs, or possibly a too-quick (or parallel? eep) reexecution of the recursive invocations of `attemptEncrypt`. We haven't done any hacking on this to try to fix it yet.

**Comment by SamBarker** [comment] 2024-09-24 21:52
Thanks for the clear report @ddaviesbrackett-dwp 

I just want to confirm the exception is transient and things auto recover? If so I think we are acting as designed (though I'd like to verify the behaviour you're experiencing) . That's not to claim we have made the right trade offs 😉

Especially in the acks expected cases we assume producers are able to handle errors and respond appropriately as that's what they need to do anyway. So rather than park requests in the proxy while waiting for a new EDEK we fail them. Parking requests represents all sorts of performance and noisy neighbour concerns which so I think we will have a high bar around adding that kind of behaviour.

In the acks=none case I think we are free to drop the records (though we definitely need metrics around this).

**Comment by SamBarker** [comment] 2024-09-24 21:56
Oh whoops i missed the implication of the 2nd log entry we shouldn't be closing things exceptionally, I'm fairly sure we should handle that

**Comment by ddaviesbrackett-dwp** [comment] 2024-09-24 22:05
the proxy definitely autorecovers from this and doesn't end up in a stuck state. I don't know yet (but can confirm after more grovelling through the perf test logs) what we're seeing on the client side when this happens; I'd like to think the client just reconnects and reattempts production but (a) I'm not personally 100% sure how the java client acts here (b) I know some clients (ahem rdkafka) are a lot chattier than others about surfacing errors to the higher-level language bindings; we haven't even attempted to reproduce this with any of the rdkafka lineage of clients or node's kafka.js. 

I take your point about not wanting to park requests in the proxy, that makes sense. Wouldn't want a slow/squirrely KMS to cause kroxy to buffer messages for a long time. But in that case, why have 3 recursive `attemptEncrypt`s in rapid succession? (this is a curiosity question, I'm not advocating change here!!) 

> Oh whoops i missed the implication of the 2nd log entry we shouldn't be closing things exceptionally, I'm fairly sure we should handle that

I'll edit the report to make it clearer that's what's happening :)

**Comment by SamBarker** [comment] 2024-09-25 03:56
> But in that case, why have 3 recursive attemptEncrypts in rapid succession? (this is a curiosity question, I'm not advocating change here!!)

It's a good question, that I've been pondering all morning. Personally my stance on what it means to be a reliable proxy has shifted a bit. We can't make a lot of problems disappear properly but we can paper over a bunch crack. So I think it's a balance, it's better for producers if we don't error at the cost of running into tail latency blow outs and noisy neighbour starvation issues. Three retires seems like a relatively low cost to carry, but I doubt I'd be very supportive of adding it now.

**Comment by ddaviesbrackett-dwp** [comment] 2024-09-25 08:53
thinking a little more about inbandencryptionmanager, how is it that the same (destroyed) DEK gets fetched from the cache more than once on the same request-handler thread during attemtEncrypt retries? if the DEK is exhausted the key context is rotated, which synchronously invalidates the that cache entry, which should mean that the next recursive invocation of attemptEncrypt should have to wait for the Caffeine AsyncLoadingCache to complete its async load of a new DEK, shouldn't it?

**Comment by tombentley** [comment] 2024-09-25 09:49
We get the dek from the cache, we check it and maybe invalidate the cache entry. The get-and-check pattern is not atomic. So multiple racing threads can end up calling invalidate with the same cache key, but might not be talking about the same cached dek.
Moreover we invalidate like this:

```java
dekCache.synchronous().invalidate(cacheKey(encryptionScheme));
```

 The Javadoc for `invalidate()` says:

> The behavior of this operation is undefined for an entry that is being loaded (or reloaded) and is otherwise not present.

**Comment by gracegrimwood** [comment] 2024-11-19 23:23
Managed to reproduce this on OpenShift 4.17 with a single Kroxylicious in front of a standard Strimzi Kafka+Zookeeper cluster.
```
2024-11-19 23:17:01 <epollEventLoopGroup-5-1> WARN io.kroxylicious.filter.encryption.RecordEncryptionFilter:106 - failed to encrypt records, cause message: io.kroxylicious.filter.encryption.encrypt.RequestNotSatisfiable: failed to reserve an EDEK to encrypt 1 records for topic ggrimwookroxylicioustest partition 0 after 3 attempts
2024-11-19 23:17:01 <epollEventLoopGroup-5-1> WARN io.kroxylicious.proxy.internal.FilterHandler:289 - [id: 0x6a4ec58b, L:/10.128.2.28:35904 - R:my-cluster-kafka-0.my-cluster-kafka-brokers.kafka.svc/10.128.2.18:9092]: Filterrequest for RecordEncryptionFilter@1141135405 PRODUCE ended exceptionally - closing connection. Cause message io.kroxylicious.filter.encryption.encrypt.RequestNotSatisfiable: failed to reserve an EDEK to encrypt 1 records for topic ggrimwookroxylicioustest partition 0 after 3 attempts
```
To produce the load I built a simple custom image based on `apache/kafka:3.8.1` from Dockerhub, where the entrypoint was `/opt/kafka/bin/kafka-producer-perf-test.sh`. A deployment of 5 of these containers running simultaneously was the minimum I needed to reproduce this bug.

**Comment by SamBarker** [comment] 2024-11-24 22:50
@kroxylicious/developers  looking at [RecordEncryptionFilterTest](https://github.com/kroxylicious/kroxylicious/blob/3c17246e61585dd6f621887def6f7229b98574ae/kroxylicious-filters/kroxylicious-record-encryption/src/test/java/io/kroxylicious/filter/encryption/RecordEncryptionFilterTest.java#L207-L239) we explicitly say it should propagate the exceptions. 

Propagation has the side effect of killing the connection. Which in the case of [#1526](https://github.com/kroxylicious/kroxylicious/issues/1526) is problematic. I think we should be catching `RequestNotSatisfiable` on the produce path explicitly and returning errors to the producer, can anyone think of a reason not do so? 

I'm going to start a PR that handles that case and responds with an error to the client.

**Comment by k-wall** [comment] 2024-12-05 17:50
@SamBarker with the work of #1630 merged, what remains to be done?

**Comment by SamBarker** [comment] 2024-12-06 00:59
We haven't done anything to address the actual request not satisfiable exception. We've fixed the fact it was closing the connection rather than erroring and we've been looking at the logging and I think @robobario found a race condition around DEK destruction from this. 

On some levels I think the `RequestNotSatisifiable` case is just the nature of doing business under load but maybe we should be offering configuration to make proactive renewal possible (say generate a new EDEK when the current DEK has less than 100 encryptions left) but that introduces a bunch of complexity around having multiple DEKs available for encryption or wasting cycles in DEK's.

@ddaviesbrackett-dwp @alanrobinson-dwp what do you think? Does what we have meet your needs?

Actually I think this issue is fixed and we should start a discussion or raise a new issue around proactive refresh of DEKs if people think its needed.

**Closed by SamBarker** 2024-12-06 00:59 UTC
Labels: bug, triaged

**Comment by robobario** [comment] 2024-12-06 01:47
the connection close is converted to an error response, but there are several issues that can happen at rollover time:

### 1. the DEK key can be invalidated from the cache multiple times by different threads

As Tom mentioned:
  > We get the dek from the cache, we check it and maybe invalidate the cache entry. The get-and-check pattern is not atomic. So multiple racing threads can end up calling invalidate with the same cache key, but might not be talking about the same cached dek. 

This is addressed in #1643. This means that the freshly created DEK may be removed from the cache immediately. So the exhaustion of 1 DEK could require the loading of several new DEKs before things settle down.
 
 ### 2. race condition at destruction time prevents retries and wastes last allocated batch of encryptions
   
Then in fixing that I found further race conditions around destruction:

Thread 1 destroying DEK A for encryption could prevent thread 2 that has successfully been allocated the number of required encryptions from obtaining an Encryptor. Currently the DestroyedDekException thrown isn't handled and would prevent re-attempting, it would just fail immediately
```java
 if (remainingEncryptions.addAndGet(-numEncryptions) >= 0) {
            // some other thread who couldn't get the desired encryptions destroys the DEK before I can get an encryptor
            if (!outstandingCryptors.acquireEncryptorUsage()) {
                throw new DestroyedDekException();
            }
```

So there's two things, the race condition causes wasted encryptions, because a thread can be allocated 100 encryptions and then have the DEK destroyed. Then because we don't handle it this doesn't cause a retry.

The fix is to add some co-ordination so that if thread A initiates a rotation (DEK destroy for encrypt + invalidate from cache), other threads with a reference to that DEK can chain onto a future to react to the rotation finishing (and it will only be invalidated from the cache once). Retries will take place after invalidation.

### 3. retry count is low under test conditions

The retry count of 3 is quite low when you reduce the maximum number of encryptions. Like in my testing at the extreme with 1 encryption per DEK, if you have 5 threads trying to obtain the one DEK then it's easy for a thread to hit the retry limit of 3 as it's only got a 1/5 chance of getting a DEK it's able to use.  Under load with bigger batches of messages we'd probably observe the same thing even with hundreds of encryptions per DEK. With the other race conditions sorted out and a more production sized max encryptions per DEK it shouldn't be an issue. I think we could safely increase it, or make it time based, like a `maxAquireUsableEdekDuration=10s`.

Point 1. is the bigger issue, but 2 and 3 make it hard to test the fix

**Comment by alanrobinson-dwp** [comment] 2024-12-06 09:32
> @ddaviesbrackett-dwp @alanrobinson-dwp what do you think? Does what we have meet your needs?

Hi Sam, yes, I think it's good for us as is. I'll let @ddaviesbrackett-dwp mull it over from the further updates in case I've missed anything though

**Comment by ddaviesbrackett-dwp** [comment] 2024-12-06 09:45
I think we're happy as is - an error response on production is plenty good enough for producing clients to retry (and almost definitely succeed).

The robustness improvements around key rotation are definitely nice to have, but we had to push our environment way harder than our current expected production load to see this at all so I don't have much to contribute around the number-of-messages DEK exhaustion scenario(s).
