### ISSUE TITLE
TimeoutException error logged when KafkaClusterIT

### ISSUE THREAD

**Issue by tombentley** [kroxylicious/kroxylicious#126] opened 2023-02-03 14:57 UTC
When running io.kroxylicious.proxy.KafkaClusterIT the following error gets logged

> 2023-02-03 14:52:07 ERROR org.apache.kafka.controller.QuorumController:445 - [Controller 0] maybeBalancePartitionLeaders: unable to start processing because of TimeoutException.
Formatting /tmp/kafka9519135150772298755/broker-0 with metadata.version 3.3-IV0.

We should investigate and fix this.

**Comment by aaditya9899** [comment] 2023-02-10 08:34
can it be assigned to me?

**Comment by tombentley** [comment] 2023-02-10 10:14
@aaditya9899 sure, done.

**Comment by aaditya9899** [comment] 2023-02-10 10:39
Thankx and just a little help, can I know to proceed with it. I mean where's the code base and what i should be looking for?

**Comment by tombentley** [comment] 2023-02-10 11:09
@aaditya9899 well it's a error that's coming from Apache Kafka. It might be because of how we're running the Kafka broker for the tests. The first thing to do is understand what better what is timing out and why. You could do that by putting a breakpoint on QuorumController:445 and trying understand the context at that point (e.g. from the callstack). But this would require some decent Kafka knowledge. I'm beginning to think may this this an `easy-starter` issue.

**Comment by aaditya9899** [comment] 2023-02-10 11:53
Thankx for this info let me first try then

**Comment by aaditya9899** [comment] 2023-02-12 08:57
where to find the quorum controller?

**Comment by SamBarker** [comment] 2023-02-13 01:36
@aaditya9899 The QuorumController is part of the Apache Kafka project and can be found on [GitHub](https://github.com/apache/kafka/blob/trunk/metadata/src/main/java/org/apache/kafka/controller/QuorumController.java#L437).

I think I've linked to the place @tombentley was discussing but the line numbers don't match exactly and I'm not sure which branch Tom was thinking of.

**Comment by franvila** [comment] 2023-03-01 14:06
Just in case it could help to resolve this issue. I saw in the logs that the error happens only in the shutdown process:

`2023-03-01 13:35:26 INFO  org.apache.kafka.raft.KafkaRaftClient:2287 - [RaftManager nodeId=0] Beginning graceful shutdown
2023-03-01 13:35:26 INFO  org.apache.kafka.raft.KafkaRaftClient:2413 - [RaftManager nodeId=0] Graceful shutdown completed
2023-03-01 13:35:26 INFO  org.apache.kafka.queue.KafkaEventQueue:404 - [Controller 0] QuorumController#beginShutdown: shutting down event queue.
2023-03-01 13:35:26 ERROR org.apache.kafka.controller.QuorumController:445 - [Controller 0] maybeBalancePartitionLeaders: unable to start processing because of TimeoutException.
2023-03-01 13:35:26 DEBUG org.apache.kafka.queue.KafkaEventQueue:401 - [Controller 0] KafkaEventQueue#close: Event queue is already shutting down.
2023-03-01 13:35:26 INFO  org.apache.kafka.queue.KafkaEventQueue:424 - [Controller 0] closed event queue.`

but I cannot find the root cause of the issue

**Comment by robobario** [comment] 2024-03-20 09:24
Closing stale - we can reopen if we see these exceptions again

**Closed by robobario** 2024-03-20 09:24 UTC
Labels: bug, easy-starter
